# Generated by Django 2.2.7 on 2019-11-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('time_apply', models.DateTimeField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='datamodel.User')),
            ],
            options={
                'db_table': 'appeal',
            },
        ),
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=200)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(default='', max_length=20)),
                ('state', models.BooleanField(default=True)),
                ('time_finish', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyrights', to='datamodel.User')),
            ],
            options={
                'db_table': 'copyright',
            },
        ),
        migrations.CreateModel(
            name='AppealJudgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.NullBooleanField(default=None)),
                ('time_judge', models.DateTimeField()),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='datamodel.Appeal')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgements', to='datamodel.User')),
            ],
            options={
                'db_table': 'appeal_judgement',
            },
        ),
        migrations.AddField(
            model_name='appeal',
            name='origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='datamodel.Copyright'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='same',
            field=models.ManyToManyField(related_name='_appeal_same_+', to='datamodel.Copyright'),
        ),
    ]
