# Generated by Django 2.2.7 on 2019-11-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20191127_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealjudgement',
            name='time_judge',
            field=models.DateTimeField(null=True),
        ),
    ]
