# Generated by Django 2.2.7 on 2019-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191127_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-time_apply']},
        ),
        migrations.AlterModelOptions(
            name='copyright',
            options={'ordering': ['-time_finish']},
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
