# Generated by Django 2.2.7 on 2019-11-27 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191127_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('state', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_pay', models.DateTimeField(null=True)),
                ('pic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='datamodel.Copyright')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='datamodel.User')),
            ],
            options={
                'db_table': 'bill_pic',
                'ordering': ['-time_create'],
            },
        ),
    ]
