# Generated by Django 2.2.7 on 2019-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_copyright_dhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_pic_similarity', models.BooleanField(default=True)),
                ('threshold_for_hamming_in_pic_similarity', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'config_client',
            },
        ),
    ]
