# Generated by Django 2.2.7 on 2019-12-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_clientconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSFunction',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('enable', models.NullBooleanField(default=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('needVerify', models.NullBooleanField(default=True)),
            ],
            options={
                'db_table': 'function_cms',
            },
        ),
        migrations.CreateModel(
            name='CMSRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enable', models.BooleanField(default=True)),
                ('category', models.CharField(default='', max_length=100)),
                ('level', models.IntegerField(default=10000)),
                ('functions', models.ManyToManyField(related_name='_cmsrole_functions_+', to='datamodel.CMSFunction')),
                ('parent_role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_roles', to='datamodel.CMSRole')),
            ],
            options={
                'db_table': 'role_cms',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(default='', max_length=254)),
                ('name', models.CharField(db_index=True, default='', max_length=15)),
                ('system_role', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='datamodel.CMSRole')),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
    ]
