# Generated by Django 2.2.7 on 2019-12-06 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_adminuser_cmsfunction_cmsrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appid',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qtoken',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage_cert',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CertRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(default=1)),
                ('name', models.CharField(default='', max_length=30)),
                ('certificate', models.ImageField(upload_to='static/certificate/%y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cert_records', to='datamodel.User')),
            ],
            options={
                'db_table': 'cert_record',
            },
        ),
    ]
