# Generated by Django 2.2.7 on 2019-12-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0010_auto_20191206_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='EContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=256)),
                ('file', models.FileField(upload_to='static/contract/%y/%m/%d')),
                ('stage', models.IntegerField(default=0)),
                ('address', models.CharField(default=None, max_length=40, null=True)),
                ('time_deploy', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'ethereum_contract',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='certrecord',
            options={'ordering': ['-id']},
        ),
    ]
